spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:secrets/application-common.yml
      - classpath:secrets/application-local.yml

---

spring:
  config:
    activate:
      on-profile: develop
    import:
      - classpath:secrets/application-common.yml
      - classpath:secrets/application-develop.yml

---

spring:
  config:
    activate:
      on-profile: production
    import:
      - classpath:secrets/application-common.yml
      - classpath:secrets/application-production.yml

---

spring:
  profiles:
    active: local
  application:
    name: noongil
  config:
    import:
